version: '3.7'
services:
  ldap_server:
    image: osixia/openldap:latest
    command: --copy-service
    environment:
      - LDAP_ADMIN_PASSWORD=1234
      - "LDAP_BASE_DN=dc=devtoppers,dc=com"
      - LDAP_ORGANISATION=devtoppers
      - LDAP_DOMAIN=devtoppers.com
    ports:
      - 389:389
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
  ldap_server_admin:
    image: osixia/phpldapadmin:0.7.2
    ports:
      - 80:80
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap_server
      PHPLDAPADMIN_HTTPS: 'false'
volumes:
  ldap_data:
  ldap_config: